language: ruby
sudo: false

rvm:
  - 2.3.0

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.10.0
  - nvm use v5.10.0
  - nvm install -g gulp-cli

before_script:
  - npm install

script:
  - bundle exec jekyll build
  - gulp build
