language: node_js
sudo: false

node_js:
  - 5.11.0

before_install:
  - rvm install 2.3.0
  - nvm install -g gulp-cli

before_script:
  - bundle install

script:
  - bundle exec jekyll build
  - gulp build
