language: node_js
sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - node_modules

node_js:
  - 5.11.0

before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.3.0
  - npm install -g gulp-cli

before_script:
  - gem install bundler
  - bundle install

script:
  - gulp build

deploy:
  provider: gcs
  access_key_id:
    secure: "GvCBZNakK4r4cvbgAUjw/thrhCe5V0AdCrQZHwyFDcO2ziBktdNtZSS4hIBBbr80R8BKtyH80P/2JgogMGIiMyc6/1OaS1Ea2YxyfOQvT95q2MK9/qBHFSe+w6JODXfkbPCRIS6SlqYmaApY3LYldFSx0JLF6+bOMjnfX4Lgk8w="
  secret_access_key:
    secure: "W/kEioAklO0/pc8ycte60XaAfgEn7PSHMDKdCaibQ8xiQd7J2P8p21GmtJmbpwEGZMr5ZfMLQ+NBbBV9JzqxPFlaJxIZYQZnw6jRCdN9GArKCYelut2LSg3Zk/ui3bWk135WPRxYLCj8FittPyEAyvAPmXx78fRQth5R+7kDXAY="
  local_dir: _site
  bucket: "si.mpli.st"
  acl: public-read
  cache_control: "max-age=1800"
  detect_encoding: true
  skip_cleanup: true
  on:
    branch: master
