language: node_js
sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - node_modules

node_js:
  - 5.11.0

before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.3.3
  - npm install -g gulp-cli

before_script:
  - gem install bundler
  - bundle install

script:
  - gulp build
