language: node_js
sudo: false

cache:
  bundler: true
  directories:
    - node_modules

node_js:
  - 5.11.0

before_install:
  - rvm install 2.3.0
  - npm install -g gulp-cli

before_script:
  - bundle install

script:
  - gulp build
