name: si.mpli.st
description: si.mpli.st by minku lee

encoding: utf-8

plugins: [jekyll-paginate]

author: Minku Lee
paginate: 15
paginate_path: "p:num"
permalink: none

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

domain: https://si.mpli.st

exclude: ["node_modules", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]
timezone: Asia/Seoul
