name: si.mpli.st
description: si.mpli.st by premist

encoding: utf-8

author: premist
pygments: true
paginate: 10
paginate_path: 'p:num'
permalink: none
markdown: redcarpet
domain: http://si.mpli.st

flickr:
  api_key: kjh3g4kj1h2gkjh1gvbnvd7o1khmqjh2g3