name: si.mpli.st
description: si.mpli.st by minku lee

encoding: utf-8

gems: [jekyll-paginate]

author: minku lee
paginate: 10
paginate_path: "p:num"
permalink: none

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

domain: http://si.mpli.st

exclude: ["node_modules", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]
timezone: Asia/Seoul
