baseURL = "https://si.mpli.st/"
languageCode = "ko-kr"
title = "si.mpli.st"
theme = "si.mpli.st"

PygmentsUseClasses = true
PygmentsCodeFences = true

[permalinks]
  post = "/post/:filename"
  travel = "/travel/:filename"
  dev = "/dev/:filename"
  geek = "/geek/:filename"
  life = "/life/:filename"
  review = "/review/:filename"
  think = "/think/:filename"

[params]
  author = "Minku Lee"
  authorWebsite = "https://premi.st"
