baseURL = "https://si.mpli.st/"
languageCode = "ko-kr"
title = "si.mpli.st"
theme = "simplist2022"

paginate = 5

PygmentsUseClasses = true
PygmentsCodeFences = true

[markup.goldmark.renderer]
unsafe = true

[outputFormats]

[outputFormats.RSS]
baseName = "feed"

[permalinks]
  post = "/post/:filename"
  travel = "/travel/:filename"
  dev = "/dev/:filename"
  geek = "/geek/:filename"
  life = "/life/:filename"
  review = "/review/:filename"
  think = "/think/:filename"

[params]
  title = "si.mpli.st"
  description = "si.mpli.st is a tiny little journal by minku lee."
  author = "Minku Lee"
  authorWebsite = "https://premi.st"
  authorFacebook = "https://www.facebook.com/premist.lee"
